# Generated by Django 5.2.8 on 2025-11-10 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('postal_code', models.CharField(blank=True, default='', max_length=15)),
                ('street', models.CharField(blank=True, default='', max_length=255)),
                ('house_number', models.CharField(blank=True, default='', max_length=15)),
                ('apartment_number', models.CharField(blank=True, default='', max_length=15)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('latitude__isnull', False), ('longitude__isnull', False)), fields=('latitude', 'longitude'), name='unique_lat_lon_not_null'), models.UniqueConstraint(fields=('city', 'postal_code', 'street', 'house_number', 'apartment_number'), name='unique_address_not_null'), models.CheckConstraint(condition=models.Q(models.Q(models.Q(models.Q(('city', ''), _negated=True), models.Q(('street', ''), _negated=True), models.Q(('house_number', ''), _negated=True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR')), name='check_valid_waypoint_data')],
            },
        ),
        migrations.CreateModel(
            name='RouteWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='routes.route')),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='routes.waypoint')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('route', 'sequence'), name='unique_route_sequence')],
            },
        ),
    ]
